[theme]
# Primary accent color for interactive elements.
primaryColor = "#eeb7ff"

# Background color for the main content area.
backgroundColor = "#00674f"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#00523F"

# Color used for almost all text
textColor = '#000000'

[client]
toolbarMode = "minimal"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"